### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by zombicadavre** [Hotrian/OVRdrop-Public#20] opened 2017-04-05 22:38 UTC
I have several "not responding" problem today, it was happened before also.

How does this happen? I play some time then I notice in HMD that capture freezes, I select OVRdrop window then voila: application not responding. This time I played ETS2, previous time I played nothing just test overlay function, if I remember correct.

Here I attach Output_log and steamvr report

[steamvr report.txt](https://github.com/Hotrian/OVRdrop-Public/files/900957/steamvr.report.txt)
[output_log.txt](https://github.com/Hotrian/OVRdrop-Public/files/900958/output_log.txt)

Regards

**Comment by Hotrian** [comment] 2017-04-05 23:01
So from your output log it's clear you're having capture issues:

> Capture Error: CaptureFailed
> Lost output, retrying..

> HCA: Failed to duplicate Adapter: 1 Output: 0
> Capture Error: CaptureFailed
> Failed to grab capture

> Capture Error: LostAccess
> Lost output, retrying..

However, what isn't clear is why.

The CaptureFailed error means that Windows is denying access for some reason. I will improve my error handling here so we can find out why.

The LostAccess error means that desktop context has been lost for some reason. This can happen in certain instances, such as when the Window's DWM restarts.

Are you using a 32bit or 64bit OS?

**Comment by zombicadavre** [comment] 2017-04-06 00:35
I'm using 64bit OS.

**Comment by Hotrian** [comment] 2017-04-06 00:38
Strange - this is built and tested on Windows 10 x64, same version as you're using.

I will continue to look into this more, but unfortunately your logs don't seem to reveal why this is happening and it hasn't happened to me so I'm not sure I'll be able to find the cause right now.

Can you try verifying the integrity of OVRdrop through Steam just in case?

**Comment by zombicadavre** [comment] 2017-04-06 00:48
OK I'll try.

**Comment by Hotrian** [comment] 2017-04-06 02:47
I just updated the Experimental Branch to give slightly better error messages. Can you switch to the Experimental Branch and see if you can get some errors again, and then upload your `output_log.txt` again?

Thanks

**Comment by zombicadavre** [comment] 2017-04-06 18:56
I'll send output_log.txt as soon as I catch error again. Stay tuned :)

**Comment by zombicadavre** [comment] 2017-04-07 21:39
[output_log.txt](https://github.com/Hotrian/OVRdrop-Public/files/906934/output_log.txt)

**Comment by Hotrian** [comment] 2017-04-07 21:56
Very strange - OVRdrop froze from this? It should have recovered just fine.

**Comment by Hotrian** [comment] 2017-04-07 22:05
I'll try pushing out an update later today with even more error handing - right now, can you try launching Steam as Admin? That should launch OVRdrop as Admin and fix any permission issues you might be encountering.

**Comment by zombicadavre** [comment] 2017-04-08 01:32
It happens after a while and maybe after some actions, but I can't tell what exactly correlates with the problem. Possibly I will be more lucky to catch what actually cause the problem.

You say OVRdrop should recover, I'll try more patience next time, but I cannot say I was waiting too little :)

Okay, I'll try launch Steam as Admin, but if I have chance to resolve freeze this way, how can I be sure that I just don't encounter this problem just because of luck? I don't sure what cause this, so I can only wait until it happens.

**Comment by Hotrian** [comment] 2017-04-08 01:41
> You say OVRdrop should recover, I'll try more patience next time, but I cannot say I was waiting too little :)

It should happen very quickly, like just a few seconds. If it is freezing then it is not recovering properly.

> I'll try launch Steam as Admin, but if I have chance to resolve freeze this way, how can I be sure that I just don't encounter this problem just because of luck

You'll just have to try it and see if you can get OVRdrop to freeze again. I can't get it to freeze on my system so I can't even begin to reproduce the issue - I can just add more error handling until I can get enough information from your crashes to track down what's going on.

**Comment by Hotrian** [comment] 2017-04-11 11:39
I think I have fixed this one - I completely rewrote the capture driver and it seems to be able to recover properly now. I have to finish incorporating it into OVRdrop but the next patch should hopefully fix this issue.

**Comment by Hotrian** [comment] 2017-04-12 09:41
Can you try the new `v1.0.4p4` on the `Experimental` branch when you get a chance? I think this one is fixed - I still don't know what was causing you to lose capture access, but it should self fix now.

**Comment by zombicadavre** [comment] 2017-04-13 06:33
Good news! I'll try it as soon as possible.

**Comment by zombicadavre** [comment] 2017-04-17 05:12
I have no problems with this bug. I'll post here if suddenly I catch it again.

I changed GPU by the way, I hope it does not affect the issue.

**Comment by Hotrian** [comment] 2017-04-17 05:36
Thanks for the update!

I marked this for the Experimental Branch since it is included there. 

Planning to close all the issues marked for the `Experimental Branch` when I push the Experimental Build to the Main Branch. 

If it does happen again, please let me know and attach your `output_log.txt`. 

Thanks again :).

**Comment by Hotrian** [comment] 2017-04-20 04:02
This fix is in the latest version which should be on the Main branch soon so closing this issue.

If it happens again please let me know.

**Closed by Hotrian** 2017-04-20 04:02 UTC
Labels: Bug, Experimental Branch
