### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by midnightspeeder** [Hotrian/OVRdrop-Public#32] opened 2017-04-20 08:54 UTC
Hey just bought and downloaded v1.0.5 and as soon as it gets past the "made with unity" screen it crashes immediately.  

[output_log.txt](https://github.com/Hotrian/OVRdrop-Public/files/941686/output_log.txt)

**Comment by Hotrian** [comment] 2017-04-20 08:59
What OS are you running? 32bit or 64bit?

**Comment by Hotrian** [comment] 2017-04-23 18:35
You confirmed on Steam that you're running Windows 7, so I'm closing this issue because it is due to your OS being unsupported, and not an actual bug with the software.

I do intend to support Windows 7 in the future, but unfortunately there are more pressing issues right now  that I'd like to take care of first.

If you need something _now_ that supports Windows 7, please consider [OpenVRDesktopDisplayPortal](https://github.com/Hotrian/OpenVRDesktopDisplayPortal). OVRDDP eventually got upgraded and became OVRdrop, but OVRDDP is free and should work on Windows 7. The downside is it can only capture about 360p at 24FPS+, and it uses quite a bit of CPU to do so. OVRdrop by contrast can capture 1440p at 200FPS+, and uses very little CPU to do so.

**Closed by Hotrian** 2017-04-23 18:35 UTC
