### ISSUE TITLE
Cursor position sometimes incorrect

### ISSUE THREAD

**Issue by tapanij** [Hotrian/OVRdrop-Public#19] opened 2017-04-05 17:53 UTC
I don't yet know how to reproduce this. Sometimes in VR the cursor appears to be in a wrong position, for example it's shifted X amount to left. Loading a profile again fixes it.

**Comment by Hotrian** [comment] 2017-04-05 22:08
Very strange. Would love if you could find a way to reproduce this - in my testing the cursor position always seems correct. If I happens again, open the Steam Dashboard (so you get the laser pointer) to confirm it is offset from its regular position. 

What HMD are you using?

**Comment by tapanij** [comment] 2017-04-05 22:10
Vive

**Comment by tapanij** [comment] 2017-04-08 19:39
It happened again. In vr the cursor had a offset to right 50% of the screen width, I use only one monitor. I was using a real mouse, it broke vive controller input same time. Couldn't take a screenshot because windows won't show the actual cursor in screenshots. Also couldn't reproduce, tried everything. Before it happened I was scaling and moving the window with two controllers and saved a profile, not sure what else.

**Comment by Hotrian** [comment] 2017-04-13 09:37
Did you by chance use the `Toggle Overlay` hotkey (defaults to `Spacebar`)? A user on Steam identified that this broke the cursor position and prevented aiming in VR.

I believe I fixed this - will do some more testing, but looks like it was due to some legacy code that never got removed.

**Comment by Hotrian** [comment] 2017-04-13 11:01
I think this is fixed now so marking for `Experimental Branch` as this should be fixed in `v1.0.4p5` which is now live on the experimental branch - if it happens again, please let me know.

**Comment by Hotrian** [comment] 2017-04-20 04:04
This fix is in the latest version which should be on the Main branch soon so closing this issue.

If it happens again please let me know.

The cursor is still a little off (10 pixels or so?) on the Oculus Touch but otherwise should be correct. The issue here is I don't have the Touch models **perfectly** aligned with the actual controllers, so there is a very small offset. Not a real issue at all IMO, and not noticeable unless you have the SteamVR Dashboard open while messing with OVRdrop. I still intend to fix that small offset but otherwise this issue should be closed.

**Closed by Hotrian** 2017-04-20 04:04 UTC
Labels: Bug, Experimental Branch
