### ISSUE TITLE
Hotkey to toggle controller input on/off

### ISSUE THREAD

**Issue by tapanij** [Hotrian/OVRdrop-Public#17] opened 2017-04-05 17:46 UTC
This would be useful to prevent accidental clicks when playing a VR game.

**Comment by Hotrian** [comment] 2017-04-06 02:49
This is now available in the Experimental Branch - could you give it some testing for me?

You'll have to enable `Background Input` on that Hotkey if you need to select some window other than OVRdrop.

It's in the bottom right of the Hotkey Settings panel, and titled `Toggle Input Enabled` - by default it isn't mapped to anything right now, so you'll have to map it to use it.

**Comment by tapanij** [comment] 2017-04-06 17:51
I'll test next time I play table tennis, this week. Not sure when.

**Comment by tapanij** [comment] 2017-04-08 02:02
Works fine but the first time I tried it I couldn't re-enable input back, had to restart the app and after that it worked as intended. Again I don't know how to reproduce.

**Comment by Hotrian** [comment] 2017-04-08 02:05
Thanks! I will look into it and see if I can reproduce.

**Comment by Hotrian** [comment] 2017-04-11 06:07
So, I haven't been able to reproduce this. It's possible it bugged out on your first launch due to something to do with the config file's new setup perhaps?

I've tried deleting my configs but haven't been able to reproduce any issues with this, so I'm not sure - it may have been an issue specifically due to migrating the config and not creating a new one.

I think it would be useful to add some sort of indicator when Input is disabled, like a little lock icon in the corner of the Overlay or something.

If it happens again, can you attach the `output_log.txt` before restarting OVRdrop, please? The output log is unfortunately cleared each time you start OVRdrop so you have to back it up before you restart or the log of what happened is lost.

**Comment by tapanij** [comment] 2017-04-11 14:57
I have no idea. Sure!

**Comment by Hotrian** [comment] 2017-04-20 04:06
This feature is in the latest version which should be on the Main branch soon so closing this issue.

If you have that issue again please let me know. I didn't have any issue enabling/disabling input, but I also only tested that specific feature for maybe 20 minutes.

**Closed by Hotrian** 2017-04-20 04:06 UTC
Labels: Experimental Branch, Feature Request
